
<script>var currencyValue='AED';var quantityValue = 2500;var yearsValue = 15;
var selectedValue=12;var interest=10;var yearInputField=document.getElementById('yearlyGrow');var rateInputField = document.getElementById('returnRate'); const data = [];const year = [];const profitValue = [];var totalDeposited = 0;var totalReaturn = 0;let chart;
const sliderEl=document.querySelector("#range");sliderEl.addEventListener("input", (event) => {const tempSliderValue = event.target.value;yearInputField.value = tempSliderValue;
var element=document.querySelector('.suffix');if(tempSliderValue<10){element.style.right = "39px";}else{element.style.right = "30px";}yearsValue=tempSliderValue;const progress=(tempSliderValue/sliderEl.max) * 100;sliderEl.style.background = `linear-gradient(to right, #01ECC4 ${progress}%, #000 ${progress}%)`;
calculateCompoundInterest(quantityValue,interest,selectedValue,yearInputField.value);});
const sliderE2 =document.querySelector("#range-2")
sliderE2.addEventListener("input",(event) => {const tempSliderValue = event.target.value; rateInputField.value = tempSliderValue; var element = document.querySelector('.suffix-2');
if(tempSliderValue<10){element.style.right="52px";}else{element.style.right="44px";}interest=tempSliderValue;const progress=(tempSliderValue/sliderE2.max)*100;sliderE2.style.background = `linear-gradient(to right, #01ECC4 ${progress}%, #000 ${progress}%)`;calculateCompoundInterest(quantityValue,rateInputField.value, selectedValue, yearsValue);});function updateValue(){quantityValue=document.getElementById("depositeAmount").value;calculateCompoundInterest(quantityValue,interest,selectedValue,yearsValue);}var radioButtons = document.querySelectorAll('input[type=radio][name=contribution_period]');
radioButtons.forEach(function(radio){radio.addEventListener('change',function(){handleFrequencyChange(this);});});function handleFrequencyChange(selectedRadio){var selectedValue=selectedRadio.value;
calculateCompoundInterest(quantityValue,interest,selectedValue,yearsValue);}function yearGrowValue() {yearsValue = document.getElementById("yearlyGrow").value;var radioButtons = document.getElementsByName("contribution_period");
for (var i=0;i<radioButtons.length;i++){if(radioButtons[i].checked) {selectedValue=radioButtons[i].value;break;}} calculateCompoundInterest(quantityValue, interest, selectedValue, yearsValue);}
const formateU=document.querySelector("#depositeAmount");formateU.addEventListener("input",(event)=>{var depositInput = document.getElementById('depositeAmount');var inputValue=parseInt(depositInput.value.replace(/,/g, ''), 10);if (!isNaN(inputValue)){depositInput.value = inputValue.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");}}); function getIntrestValue() {interest = document.getElementById("returnRate").value;calculateCompoundInterest(quantityValue, interest, selectedValue, yearsValue);}
function handleButtonClick(){alert('Button Clicked!');calculateCompoundInterest(quantityValue,interest,selectedValue,yearsValue);}function calculateCompoundInterest (principal,rate,compoundingFrequency,time) {principal=principal.toString().replace(/[^\d.]/g, '');principal = parseInt(principal.toString().replace(/,/g, ''));
year.length=0;data.length = 0;profitValue.length=0;let currentDate = new Date();var n=compoundingFrequency;var r = rate / 100;var t = time;var yearIncreasedByOne=0;var totalValue = 0;var depositedAmount=0;var compoundingsPerYear=compoundingFrequency;for (var i = 1; i <= t * compoundingsPerYear; i++) {var currentMonthInterest = principal * Math.pow(1 + r / n, n * (i / compoundingsPerYear));
totalValue+=currentMonthInterest;depositedAmount=depositedAmount + parseInt(principal);if (parseInt(compoundingsPerYear)==12){if(i%12===0){year.push(currentDate.getFullYear() + yearIncreasedByOne);data.push(depositedAmount);var k = totalValue - depositedAmount;profitValue.push(forma(k.toString()));yearIncreasedByOne += 1;}}else if(parseInt(compoundingsPerYear) == 365) {
if (i%365===0){year.push(currentDate.getFullYear()+yearIncreasedByOne);data.push(depositedAmount); var k=totalValue-depositedAmount;profitValue.push(forma(k.toString()));yearIncreasedByOne += 1;}} else if (parseInt(compoundingsPerYear) == 52) {if (i % 52 === 0) {year.push(currentDate.getFullYear() + yearIncreasedByOne);
data.push(depositedAmount);var k=totalValue-depositedAmount;profitValue.push(forma(k.toString()));yearIncreasedByOne += 1;}} else {if (i % 1 === 0) {year.push(currentDate.getFullYear() + yearIncreasedByOne);data.push(depositedAmount);var k=totalValue - depositedAmount;profitValue.push(forma(k.toString()));yearIncreasedByOne += 1;}}}totalDeposited = depositedAmount;totalReaturn = totalValue.toFixed("2");
if (chart==null) {createBarGraph();}else{chart.destroy();createBarGraph();}} function createBarGraph() {showRes = document.getElementById('return-result');currencySymbolValue = document.getElementById('currency-text');
if(currencySymbol(currencyValue)=='AED  '){currencySymbolValue.style.fontSize='30px';}else{currencySymbolValue.style.fontSize = '40px';}currencySymbolValue.textContent = currencySymbol(currencyValue);showRes.textContent = formateNumers(totalReaturn.toString());showInv = document.getElementById('invest-result');showRet = document.getElementById('ret-result');showInv.textContent = "Investment  "+currencySymbol(currencyValue)+formateNumers(data[data.length - 1].toString());showRet.textContent = "Return  "+currencySymbol(currencyValue)+formateNumers(profitValue[data.length - 1].toString());
const ctx = document.getElementById('myChart');const thickness=Math.max(5,ctx.width / data.length);chart = new Chart(ctx, {type: 'bar',data: {labels: year,datasets: [{
label:"Investment",data:data,borderWidth: 0,backgroundColor:"#175F52",borderRadius:50,barThickness: thickness},{label:"Return",data: profitValue,borderWidth: 0,backgroundColor: "#01ECC4", borderRadius: 50,barThickness: thickness,color: "white"
},]},responsive:true,options:{plugins: {legend:{display: false,position: 'top',}},scales: {y:{stacked: true,beginAtZero: true,display: false,},x: { stacked: true,ticks: { color: 'white', },}}}});}function formateNumers(val) {let inputValue=val.replace(/\.\d*/g, '');return Number(inputValue).toLocaleString();}function formatNumber(input) {let inputValue = input.value.replace(/\D/g,'');let formattedValue=Number(inputValue).toLocaleString();
input.value=currencySymbol(currencyValue)+formattedValue;}function forma(val){let inputValue=val.replace(/\.\d+/g, '');return parseInt(inputValue);}function formatCurrency(getValue){var numericValue = getValue.replace(/[^\d.]/g, '');numericValue = numericValue.replace(/\D/g, '');return Number(numericValue).toLocaleString();;}function currencySymbol(curen) {if (curen =='AED') {return 'AED  ';} else if (curen == 'USD') {
return '$  ';} else {return '₹  ';}} const dropdowns = document.querySelectorAll('.dropdown-1');dropdowns.forEach(dropdown => {const select = dropdown.querySelector('.select');const caret=dropdown.querySelector('.caret');const menu = dropdown.querySelector('.menu');var options = dropdown.querySelectorAll('.menu li');const selected = dropdown.querySelector('.selected');select.addEventListener('click', () => {select.classList.toggle('select-clicked');
caret.classList.toggle('caret-rotate');menu.classList.toggle('menu-open');});options.forEach(opt => {opt.addEventListener('click', () => {selected.innerText = opt.innerText;
select.classList.remove('select-clicked');caret.classList.remove('caret-rotate');menu.classList.remove('menu-open');options.forEach(option => {opt.classList.remove('active');});opt.classList.add('active');currencyValue=selected.innerText;curenPre = document.getElementById('prefix');
paddChange = document.getElementById('depositeAmount'); curenPre.textContent = currencySymbol(currencyValue);if(currencySymbol(currencyValue)=="AED  "){curenPre.style.fontSize='16px';curenPre.style.top = "42%";curenPre.style.right = '249px';paddChange.style.paddingLeft = '70px';}else{curenPre.style.fontSize = '20px';curenPre.style.top = "40%";curenPre.style.right = '250px';paddChange.style.paddingLeft = '50px';}quantityValue = document.getElementById("depositeAmount").value;document.getElementById("depositeAmount").value =formatCurrency(quantityValue.toString());calculateCompoundInterest(quantityValue, interest, selectedValue, yearsValue);});});});document.addEventListener("DOMContentLoaded", function () {calculateCompoundInterest(quantityValue, interest, selectedValue, yearsValue);const progress = (15 / sliderEl.max) * 100;sliderEl.style.background = `linear-gradient(to right, #01ECC4 ${progress}%, #000 ${progress}%)`;});document.addEventListener("DOMContentLoaded", function(){const progresses = (10 / sliderE2.max) * 100;sliderE2.style.background = `linear-gradient(to right, #01ECC4 ${progresses}%, #000 ${progresses}%)`;});document.getElementById("depositeAmount").addEventListener("change", updateValue);document.getElementById("yearlyGrow").addEventListener("change", yearGrowValue);document.getElementById("returnRate").addEventListener("change", getIntrestValue);
</script>
